Repository lion-packages/security, pull requests merged in 2025-03, with the labels that each got.

#18 Update PHPUnit v12
  Dockerfile
  composer.json
  phpunit.xml
Labels: dependencies

#19 Add cache in workflow
  .github/workflows/php.yml
Labels: continuous integration

#20 PHPLint is integrated
  .github/workflows/php.yml
  .gitignore
  composer.json
Labels: continuous integration, dependencies

#21 Added dependency-review in Github Actions
  .github/workflows/php.yml
Labels: continuous integration

#22 Added dependabot
  .github/dependabot.yml
  composer.json
Labels: continuous integration, dependencies
