Repository lion-packages/security, pull requests merged in 2025-04, with the labels that each got.

#24 Infection is integrated
  .github/workflows/php.yml
Labels: continuous integration

#25 Update README.md
  .github/README.md
Labels: documentation

#26 Added parameterization of the Validator object to add validations
  .gitignore
  src/LionSecurity/Validation.php
  tests/ValidationTest.php
Labels: enhancement, tests

#28 Update dependabot.yml
  .github/dependabot.yml
Labels: continuous integration

#31 Apply fixes from StyleCI
  src/LionSecurity/AES.php
  tests/RSATest.php
Labels: standardization

#30 Added StyleCI configuration
  .styleci.yml
  tests/RSATest.php
Labels: continuous integration

#32 Adding a condition to run test coverage in Github Actions (Pull Request)
  .github/workflows/php.yml
Labels: continuous integration

#33 Define the execution time for Github Actions
  .github/workflows/php.yml
Labels: continuous integration

#34 Define the runtime for the Dependabot
  .github/dependabot.yml
Labels: continuous integration
